version: '3.8'

services:
  zookeeper:
    container_name: zookeeper2
    hostname: zookeeper
    image: bitnami/zookeeper:latest
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka

  kafka:
    container_name: kafka2
    hostname: kafka
    image: 'bitnami/kafka:latest'
    user: root
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - kafka
    depends_on:
      - zookeeper

  app:
    container_name: app
    image: dockerkafka:latest
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    networks:
      - kafka

networks:
  kafka:
    driver: bridge
